# Generated by Django 4.1.6 on 2023-02-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_course_id_alter_courseallocation_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadVideo",
        ),
    ]
