# Generated by Django 4.1.6 on 2023-03-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_delete_uploadvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[("Bachiller", "Licenciatura"), ("Maestro", "Maestría")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[
                    ("Primero", "Primero"),
                    ("Segundo", "Segundo"),
                    ("Tercero", "Tercero"),
                ],
                max_length=200,
            ),
        ),
    ]
