# Generated by Django 4.1.6 on 2023-02-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_newsandevents_id_alter_semester_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsandevents",
            name="posted_as",
            field=models.CharField(
                choices=[("Noticia", "Noticia"), ("Evento", "Evento")], max_length=10
            ),
        ),
    ]
